### ISSUE TITLE
Spacing is chaotic

### ISSUE THREAD

**Issue by alicaudle** [alicaudle/call-to-action-banner#1]
All of my words are too far a part and I can't figure out how to squish them closer. Also, I don't know how to make my transformers icon the right size.
Please & thank you!!
@thomasjbradley

Ali

**Comment by alicaudle** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
Make the `width` on the icon smaller, somewhere around `30%` & the content bigger, like `60%`.

Add a line-height to the `<h2>`, I think it’s `1.2`
